Groporte.Web/Areas/Dashboard/Controllers/MessageController.cs
using Groporte.Core.Interfaces.Services;
using Groporte.Core.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Groporte.Web.Areas.Dashboard.Controllers
{
    public class MessageController : BaseController
    {
        private readonly IConversationService _conversationService;

        public MessageController(IConversationService conversationService)
        {
            _conversationService = conversationService;
        }

        // GET: Message
        public async Task<ActionResult> IndexAsync(Guid? orderId = null)
        {
            var orderMessages = await _conversationService.GetOrderMessagesAsync();

            //var orderMessageHistory = await GetOrderMessageHistoryAsync(orderId ?? orderMessages.FirstOrDefault()?.OrderId);

            //var model = new KeyValuePair<List<OrderMessage>, List<Conversation>>(orderMessages, orderMessageHistory);

            return View(orderMessages);
        }

        [HttpPost]
        public async Task<Conversation> SendMessageAsync(Conversation conversation)
        {
            var savedMessage = await _conversationService.SendMessageAsync(conversation);

            return savedMessage;
        }

        public async Task<PartialViewResult> GetOrderMessageHistoryPartialAsync(Guid? orderId = null)
        {
            var model = await _conversationService.GetConversationsAsync(orderId);

            return PartialView("_MessageHistoryPartial", model);
        }

        [HttpPost]
        public async Task<bool> IsOutgoingAsync(Guid senderId)
        {
            return await _conversationService.IsOutgoingAsync(senderId);
        }

        private async Task<List<Conversation>> GetOrderMessageHistoryAsync(Guid? orderId = null)
        {
            return await _conversationService.GetConversationsAsync(orderId);
        }
    }
}

Groporte.Web/Areas/Dashboard/Controllers/OrderController.cs
using Groporte.Core.Helpers;
using Groporte.Core.Interfaces.Services;
using Groporte.Core.SearchCriteriaModels;
using Groporte.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Groporte.Web.Areas.Dashboard.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: Order
        public async Task<IActionResult> Index(OrderSearchCriteriaModel searchCriteria)
        {
            var model = await _orderService.GetOrdersAsync(searchCriteria);

            return View(model);
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _orderService.GetOrderDetailAsync(id);

            return PartialView(model);
        }

        // GET: Order/Create
        public IActionResult Create()
        {
            var model = new SaveOrderModel();

            return PartialView(model);
        }

        // POST: Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SaveOrderModel saveOrderModel)
        {
            try
            {
                await _orderService.SaveOrderAsync(null, saveOrderModel);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                while (!ex.InnerException.IsNull()) ex = ex.InnerException;

                return BadRequest(ex.Message);
            }
        }

        // GET: Order/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await _orderService.GetSaveOrderModelAsync(id);

            return PartialView(model);
        }

        // POST: Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, SaveOrderModel saveOrderModel)
        {
            try
            {
                await _orderService.SaveOrderAsync(id, saveOrderModel);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                while (!ex.InnerException.IsNull()) ex = ex.InnerException;

                return BadRequest(ex.Message);
            }
        }

        // GET: Order/Cancel/5
        public IActionResult Cancel(Guid? id)
        {
            if (!id.HasValue) return BadRequest("Id is null");

            return PartialView();
        }

        // POST Order/Cancel/5
        [HttpPost]
        public async Task<IActionResult> Cancel(Guid id)
        {
            try
            {
                await _orderService.CancelOrderAsync(id);

                return NoContent();
            }
            catch (Exception ex)
            {
                while (!ex.InnerException.IsNull()) ex = ex.InnerException;

                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Pay(Guid id)
        {
            // todo: handle payment using escrow
            return NoContent();
        }
    }
}

Groporte.Web/Areas/Dashboard/Controllers/ProductController.cs
using Groporte.Core.Helpers;
using Groporte.Core.Interfaces.Services;
using Groporte.Core.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Groporte.Web.Areas.Dashboard.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            var model = await _productService.GetAllAsync();

            return View(model);
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _productService.GetAsync(id);

            return PartialView(model);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            var model = new Product();

            return PartialView(model);
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            try
            {
                await _productService.SaveProductAsync(null, product);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                while (!ex.InnerException.IsNull()) ex = ex.InnerException;

                return BadRequest(ex.Message);
            }
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await _productService.GetAsync(id);

            return PartialView(model);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Product product)
        {
            try
            {
                await _productService.SaveProductAsync(id, product);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                while (!ex.InnerException.IsNull()) ex = ex.InnerException;

                return BadRequest(ex.Message);
            }
        }

        // POST: Product/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _productService.DeleteAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                while (!ex.InnerException.IsNull()) ex = ex.InnerException;

                return BadRequest(ex.Message);
            }
        }
    }
}

Groporte.Web/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(ViewData["Title"] ?? "Dashboard")</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" />
    </environment>
    
    <link rel="stylesheet" type="text/css" href="~/lib/font-awesome/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/dataTables/datatables.min.css" />
    <link rel="stylesheet" href="~/css/main.min.css" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <partial name="_SidebarPartial" />
        <div id="page-content-wrapper">
            <partial name="_LoginPartial" />
            <div class="content">
                @RenderBody()
            </div>
            <div id="loading-spinner" style="display:none;">
                <div id="spinner-container">
                    <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
        <partial name="_ModalDialogPartial" />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-VoPFvGr9GxhDT3n8vqqZ46twP5lgex+raTCfICQy73NLhN7ZqSfCtfSn4mLA2EFA">
        </script>
    </environment>

    <script src="~/lib/toastr/toastr.min.js" asp-append-version="true"></script>
    <script src="~/lib/dataTables/datatables.min.js" asp-append-version="true"></script>
    <script src="~/js/app.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <script>
        app.common.initPage();
    </script>
</body>
</html>

Groporte.Web/Areas/Dashboard/Views/Shared/_MenuLinksPartial.cshtml
<nav class="nav">
    <a class="navbar-brand" href="#">Navbar</a>
    <div>
        <ul class="nav flex-column">
            <li class="nav-item active">
                <a class="nav-link" asp-area="Dashboard" asp-controller="Order" asp-action="Index">
                    Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Dashboard" asp-controller="Order" asp-action="Index">
                    Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Dashboard" asp-controller="Product" asp-action="Index">
                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Dashboard" asp-controller="Message" asp-action="Index">
                    Messages
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Dashboard" asp-controller="Order" asp-action="Index">
                    Settings
                </a>
            </li>
        </ul>
    </div>
</nav>